version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build rollup
          command: yarn build
      - run:
          name: Type check
          command: yarn type-check
      - run:
          name: Test
          command: yarn test
      - run:
          name: Eslint
          command: yarn lint
      - run:
          name: Prettier
          command: yarn prettier-eslint
