version: 2

commands:

jobs:
  install:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh
      - run:
          name: Install Dependencies
          command: yarn install

  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Build rollup
          command: yarn build:rollup

    # TODO: fix tests locally and add them to circleci

    lint:
      docker:
        - image: circleci/node:10
      steps:
        - checkout
        - run:
            name: Eslint
            command: yarn lint
        - run:
            name: Prettier
            command: yarn prettier-eslint
